CREATE TABLE "cv_records" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"surname" text,
	"id_passport" text,
	"gender" text,
	"email" text NOT NULL,
	"phone" text,
	"position" text NOT NULL,
	"role_title" text,
	"department" text,
	"experience" integer,
	"experience_similar_role" integer,
	"experience_itsm_tools" integer,
	"sap_k_level" text,
	"qualifications" text,
	"qualification_type" text,
	"qualification_name" text,
	"institute_name" text,
	"year_completed" text,
	"languages" text,
	"work_experiences" text,
	"certificate_types" text,
	"skills" text,
	"status" text DEFAULT 'pending' NOT NULL,
	"cv_file" text,
	"submitted_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "user_profiles" (
	"id" serial PRIMARY KEY NOT NULL,
	"username" varchar(50) NOT NULL,
	"email" varchar(255) NOT NULL,
	"password" varchar(255) NOT NULL,
	"role" varchar(20) DEFAULT 'user' NOT NULL,
	"first_name" varchar(100),
	"last_name" varchar(100),
	"department" varchar(100),
	"position" varchar(100),
	"phone_number" varchar(20),
	"is_active" boolean DEFAULT true,
	"last_login" timestamp,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "user_profiles_username_unique" UNIQUE("username"),
	CONSTRAINT "user_profiles_email_unique" UNIQUE("email")
);
